import 'package:flutter/material.dart';

class L10n {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_back': 'WELCOME\nBACK',
      'sign_in_continue': 'Sign in to continue your training journey.',
      'sign_in_google': 'Sign in with Google',
      'sign_in_apple': 'Sign in with Apple',
      'no_account': "Don't have an account? ",
      'sign_up_free': 'Sign up free',
      'secure_access': 'SECURE ACCESS',
      'encryption_info': 'We use industry-standard encryption to protect your data.',
      'create_account': 'CREATE YOUR\nACCOUNT',
      'join_thousands': "Join thousands of athletes training with the world's best programs.",
      'sync_info': 'Your name, email, and profile photo will be automatically synced from your Google account.',
      'have_account': 'Already have an account? ',
      'sign_in': 'Sign in',
      'get_started_fast': 'GET STARTED FAST',
      'one_tap_login': 'One-tap login means you can start your first workout in less than 30 seconds.',
      'select_language': 'Select Language',
      'my_profile': 'MY PROFILE',
      'edit_profile': 'Edit Profile',
      'your_stats': 'YOUR STATS',
      'active_program': 'ACTIVE PROGRAM',
      'weekly_activity': 'WEEKLY ACTIVITY',
      'streak': "THIS WEEK'S STREAK",
      'achievements': 'ACHIEVEMENTS',
      'account': 'ACCOUNT',
      'preferences': 'PREFERENCES',
      'units': 'Units',
      'language': 'Language',
      'rest_timer': 'Rest Timer',
      'notifications': 'Notifications',
      'dark_mode': 'Dark Mode',
      'privacy': 'Privacy',
      'support': 'SUPPORT',
      'help_center': 'Help Center',
      'feedback': 'Send Feedback',
      'terms': 'Terms & Privacy',
      'log_out': 'Log Out',
      'home_title': 'ATHLÈTE',
      'search_hint': 'Search athlete, style...',
      'no_athletes': 'No athletes found',
      'hero_category': 'BODYBUILDING LEGENDS',
      'hero_title': 'CHOOSE YOUR\nPROGRAM',
      'hero_subtitle': 'Select an athlete to explore their full training system.',
      'step': 'Step',
      'of': 'of',
      'continue': 'CONTINUE →',
      'finish_setup': 'FINISH SETUP →',
      'start_training': 'START TRAINING →',
      'skip_setup': 'SKIP FOR NOW',
      'goal_title': 'WHAT\'S YOUR\nMAIN GOAL?',
      'goal_sub': 'We\'ll personalize your program recommendations around this.',
      'build_muscle': 'Build Muscle',
      'build_muscle_desc': 'Mass & strength gain',
      'lose_fat': 'Lose Fat',
      'lose_fat_desc': 'Cut & get shredded',
      'endurance': 'Endurance',
      'endurance_desc': 'Cardio & stamina',
      'performance': 'Performance',
      'performance_desc': 'Speed & athleticism',
      'level_title': 'YOUR TRAINING\nEXPERIENCE',
      'level_sub': 'This sets the intensity and complexity of your program.',
      'beginner': 'Beginner',
      'beginner_sub': 'Under 1 year of training',
      'intermediate': 'Intermediate',
      'intermediate_sub': '1–3 years of training',
      'advanced': 'Advanced',
      'advanced_sub': '3+ years — serious athlete',
      'metrics_title': 'YOUR BODY\nMETRICS',
      'metrics_sub': 'Used to tailor your nutrition plan and track your transformation.',
      'weight': 'Weight',
      'height': 'Height',
      'age': 'Age',
      'sex': 'Biological Sex',
      'select': 'Select...',
      'male': 'Male',
      'female': 'Female',
      'days_title': 'HOW MANY DAYS\nPER WEEK?',
      'days_sub': 'Consistency beats intensity. Choose what you can realistically commit to.',
      'days_3': '3 Days',
      'days_3_desc': 'Full body focus',
      'days_4': '4 Days',
      'days_4_desc': 'Upper/lower split',
      'days_5': '5 Days',
      'days_5_desc': 'Classic PPL split',
      'days_6': '6 Days',
      'days_6_desc': 'Full commitment',
      'welcome_user': 'WELCOME,\n',
      'success_sub': 'Your profile is set up and your personalized\nprogram recommendations are ready.',
      'quiz_title': 'FIND YOUR MATCH',
      'quiz_continue': 'CONTINUE →',
      'quiz_match': 'SEE MY MATCH →',
      'quiz_result_label': 'YOUR PERFECT MATCH',
      'quiz_result_desc': 'Your drive for performance and muscle perfectly matches {name}\'s methodology.',
      'view_program': 'VIEW FULL PROGRAM →',
      'retake_quiz': 'Retake the Quiz',
      'sessions_completed': 'Sessions Completed',
      'training_time': 'Total Training Time',
      'sessions_per_week': 'Sessions per week',
      'sessions_goal': 'Last 7 weeks · goal: 6/week',
      'done': 'Done',
      'month_streak': 'This Month\'s Streak',
      'best_streak_ever': 'Best streak ever',
      'active_program_label': 'ACTIVE PROGRAM',
      'complete_label': 'complete',
      'week': 'Week',
      'total_volume': 'Total Volume Lifted',
      'goal_muscle': 'Build Muscle & Strength',
      'goal_muscle_sub': 'Hypertrophy, power, mass',
      'goal_fat': 'Lose Fat & Get Lean',
      'goal_fat_sub': 'Burn calories, cut body fat',
      'goal_endurance': 'Build Endurance & Stamina',
      'goal_endurance_sub': 'Cardio, running, long distance',
      'goal_performance': 'Athletic Performance',
      'goal_performance_sub': 'Speed, agility, sport-specific',
      'exp_beg': 'Beginner',
      'exp_beg_sub': 'Under 1 year of training',
      'exp_int': 'Intermediate',
      'exp_int_sub': '1–3 years of consistent training',
      'exp_adv': 'Advanced',
      'exp_adv_sub': '3+ years, serious athlete',
      'time_3': '3 Days a Week',
      'time_3_sub': 'Compact, efficient sessions',
      'time_5': '4–5 Days a Week',
      'time_5_sub': 'Balanced split training',
      'time_6': '6 Days a Week',
      'time_6_sub': 'Full commitment mode',
      'personal_info': 'Personal Info',
      'fitness_profile': 'Fitness Profile',
      'subscription': 'Subscription',
      'privacy_settings': 'PRIVACY SETTINGS',
      'privacy_desc': 'Your profile is currently private. Only you can see your progress.',
      'close': 'CLOSE',
      'back': 'Back',
      'exercises': 'Exercises',
      'style': 'Style',
      'intensity': 'Intensity',
      'training_program': 'Training Program',
      'focus_areas': 'Focus Areas',
      'start_this_program': 'START THIS PROGRAM',
      'gym_program_builder': 'Gym Program Builder',
      'end_session': 'END SESSION',
      'training': 'TRAINING',
      'exercise': 'Exercise',
      'elapsed': 'elapsed',
      'sets': 'SETS',
      'reps': 'REPS',
      'rest': 'REST',
      'set': 'Set',
      'prev': 'PREV',
      'next_exercise': 'NEXT EXERCISE',
      'finish_session': 'FINISH SESSION',
      'session_complete': 'SESSION COMPLETE',
      'session_done_msg': 'Great work. Rest, refuel, and come back stronger.',
      'view_my_progress': 'VIEW MY PROGRESS',
      'back_to_home': 'Back to Home',
      'bench_press': 'BENCH PRESS',
      'overhead_press': 'OVERHEAD PRESS',
      'barbell_row': 'BARBELL ROW',
      'chest_day': 'CHEST DAY',
      'nav_home': 'Home',
      'nav_quiz': 'Quiz',
      'nav_progress': 'Progress',
      'nav_profile': 'Profile',
      'performing_set': 'PERFORMING SET',
      'ready_to_start': 'READY TO START',
      'resting': 'RESTING',
      'rest_over': 'REST OVER',
      'ready_for_set': 'Are you ready for Set {num}?',
      'yes_start_set': 'YES, START SET',
      'start_set': 'START SET',
      'paused': 'PAUSED',
      'ready_next_session': 'READY FOR YOUR NEXT SESSION',
      'last_completed_session': 'LAST COMPLETED SESSION',
      'overall_completion': 'OVERALL WEEK COMPLETION',
    },
    'fr': {
      'welcome_user': 'BIENVENUE,\n',
      'sign_in_apple': 'Se connecter avec Apple',
      'select_language': 'Choisir la langue',
      'success_sub': 'Votre profil est prêt et vos recommandations personnalisées sont prêtes.',
      'quiz_title': 'TROUVER VOTRE MATCH',
      'quiz_continue': 'CONTINUER →',
      'quiz_match': 'VOIR MON MATCH →',
      'quiz_result_label': 'VOTRE MATCH PARFAIT',
      'quiz_result_desc': 'Votre motivation pour la performance et le muscle correspond parfaitement à la méthodologie de {name}.',
      'view_program': 'VOIR LE PROGRAMME →',
      'retake_quiz': 'Refaire le Quiz',
      'sessions_completed': 'Sessions terminées',
      'training_time': 'Temps d\'entraînement total',
      'sessions_per_week': 'Sessions par semaine',
      'sessions_goal': 'Dernières 7 semaines · objectif : 6/sem',
      'done': 'Terminé',
      'month_streak': 'Série du mois',
      'best_streak_ever': 'Meilleure série',
      'active_program_label': 'PROGRAMME ACTIF',
      'complete_label': 'terminé',
      'week': 'Semaine',
      'total_volume': 'Volume total soulevé',
      'goal_muscle': 'Prendre du Muscle & Force',
      'goal_muscle_sub': 'Hypertrophie, puissance, masse',
      'goal_fat': 'Perdre du Gras & Sécher',
      'goal_fat_sub': 'Brûler des calories, perdre du gras',
      'goal_endurance': 'Endurance & Stamina',
      'goal_endurance_sub': 'Cardio, course, longue distance',
      'goal_performance': 'Performance Athlétique',
      'goal_performance_sub': 'Vitesse, agilité, spécifique au sport',
      'exp_beg': 'Débutant',
      'exp_beg_sub': 'Moins d\'un an de pratique',
      'exp_int': 'Intermédiaire',
      'exp_int_sub': '1 à 3 ans de pratique régulière',
      'exp_adv': 'Avancé',
      'exp_adv_sub': 'Plus de 3 ans, athlète sérieux',
      'time_3': '3 Jours par semaine',
      'time_3_sub': 'Sessions compactes et efficaces',
      'time_5': '4–5 Jours par semaine',
      'time_5_sub': 'Entraînement split équilibré',
      'time_6': '6 Jours par semaine',
      'time_6_sub': 'Mode engagement total',
      'personal_info': 'Infos personnelles',
      'fitness_profile': 'Profil Fitness',
      'subscription': 'Abonnement',
      'privacy_settings': 'CONFIDENTIALITÉ',
      'privacy_desc': 'Votre profil est privé. Vous seul voyez votre progression.',
      'close': 'FERMER',
      'back': 'Retour',
      'exercises': 'Exercices',
      'style': 'Style',
      'intensity': 'Intensité',
      'training_program': 'Programme d\'entraînement',
      'focus_areas': 'Zones ciblées',
      'start_this_program': 'DÉMARRER CE PROGRAMME',
      'gym_program_builder': 'Générateur de Programme de Musculation',
      'end_session': 'FIN DE SESSION',
      'training': 'ENTRAÎNEMENT',
      'exercise': 'Exercice',
      'elapsed': 'écoulé',
      'sets': 'SÉRIES',
      'reps': 'REPS',
      'rest': 'REPOS',
      'set': 'Série',
      'prev': 'PRÉC',
      'next_exercise': 'EXERCICE SUIVANT',
      'finish_session': 'TERMINER LA SESSION',
      'session_complete': 'SESSION TERMINÉE',
      'session_done_msg': 'Bon travail. Reposez-vous et revenez plus fort.',
      'view_my_progress': 'VOIR MA PROGRESSION',
      'back_to_home': 'Retour à l\'accueil',
      'bench_press': 'DÉVELOPPÉ COUCHÉ',
      'overhead_press': 'DÉVELOPPÉ MILITAIRE',
      'barbell_row': 'TIRAGE BARRE',
      'chest_day': 'JOUR DES PECTORAUX',
      'skip_setup': 'IGNORER POUR L\'INSTANT',
      'nav_home': 'Accueil',
      'nav_quiz': 'Quiz',
      'nav_progress': 'Progrès',
      'nav_profile': 'Profil',
      'performing_set': 'SÉRIE EN COURS',
      'ready_to_start': 'PRÊT À DÉMARRER',
      'resting': 'REPOS',
      'rest_over': 'REPOS TERMINÉ',
      'ready_for_set': 'Prêt pour la série {num} ?',
      'yes_start_set': 'OUI, DÉMARRER',
      'start_set': 'DÉMARRER',
      'paused': 'EN PAUSE',
      'ready_next_session': 'PRÊT POUR LA PROCHAINE SESSION',
      'last_completed_session': 'DERNIÈRE SESSION TERMINÉE',
      'overall_completion': 'PROGRESSION HEBDOMADAIRE',
    },
    'ar': {
      'welcome_user': 'أهلاً بك،\n',
      'sign_in_apple': 'تسجيل الدخول باستخدام Apple',
      'select_language': 'اختر اللغة',
      'success_sub': 'تم إعداد ملفك الشخصي وتوصياتك المخصصة جاهزة.',
      'quiz_title': 'اعثر على ما يناسبك',
      'quiz_continue': 'استمرار ←',
      'quiz_match': 'رؤية ما يناسبني ←',
      'quiz_result_label': 'خيارك المثالي',
      'quiz_result_desc': 'شغفك بالأداء والعضلات يتناسب تماماً مع منهجية {name}.',
      'view_program': 'رؤية البرنامج الكامل ←',
      'retake_quiz': 'إعادة الاختبار',
      'sessions_completed': 'الجلسات المكتملة',
      'training_time': 'إجمالي وقت التدريب',
      'sessions_per_week': 'الجلسات في الأسبوع',
      'sessions_goal': 'آخر 7 أسابيع · الهدف: 6/أسبوع',
      'done': 'تم',
      'month_streak': 'سلسلة هذا الشهر',
      'best_streak_ever': 'أفضل سلسلة على الإطلاق',
      'active_program_label': 'البرنامج النشط',
      'complete_label': 'مكتمل',
      'week': 'أسبوع',
      'total_volume': 'إجمالي الحجم المرفوع',
      'goal_muscle': 'بناء العضلات والقوة',
      'goal_muscle_sub': 'تضخيم، قوة، كتلة',
      'goal_fat': 'خسارة الدهون والتنشيف',
      'goal_fat_sub': 'حرق السعرات، تقليل دهون الجسم',
      'goal_endurance': 'بناء التحمل واللياقة',
      'goal_endurance_sub': 'كارديو، جري، مسافات طويلة',
      'goal_performance': 'الأداء الرياضي',
      'goal_performance_sub': 'سرعة، رشاقة، رياضة محددة',
      'exp_beg': 'مبتدئ',
      'exp_beg_sub': 'أقل من سنة من التدريب',
      'exp_int': 'متوسط',
      'exp_int_sub': '1-3 سنوات من التدريب المستمر',
      'exp_adv': 'متقدم',
      'exp_adv_sub': 'أكثر من 3 سنوات، رياضي جاد',
      'time_3': '3 أيام في الأسبوع',
      'time_3_sub': 'جلسات مدمجة وفعالة',
      'time_5': '4-5 أيام في الأسبوع',
      'time_5_sub': 'تدريب تقسيم متوازن',
      'time_6': '6 أيام في الأسبوع',
      'time_6_sub': 'وضع الالتزام الكامل',
      'personal_info': 'المعلومات الشخصية',
      'fitness_profile': 'ملف اللياقة',
      'subscription': 'الاشتراك',
      'privacy_settings': 'إعدادات الخصوصية',
      'privacy_desc': 'ملفك الشخصي خاص حالياً. أنت فقط من يمكنه رؤية تقدمك.',
      'close': 'إغلاق',
      'back': 'رجوع',
      'exercises': 'تمارين',
      'style': 'أسلوب',
      'intensity': 'كثافة',
      'training_program': 'برنامج التدريب',
      'focus_areas': 'مناطق التركيز',
      'start_this_program': 'ابدأ هذا البرنامج',
      'gym_program_builder': 'منشئ برنامج الجيم',
      'end_session': 'إنهاء الجلسة',
      'training': 'تدريب',
      'exercise': 'تمرين',
      'elapsed': 'انقضى',
      'sets': 'جولات',
      'reps': 'عدات',
      'rest': 'راحة',
      'set': 'جولة',
      'prev': 'السابق',
      'next_exercise': 'التمرين التالي',
      'finish_session': 'إنهاء الجلسة',
      'session_complete': 'اكتملت الجلسة',
      'session_done_msg': 'عمل رائع. ارتح، وتغذى جيداً، وعد أقوى.',
      'view_my_progress': 'عرض تقدمي',
      'back_to_home': 'العودة للرئيسية',
      'bench_press': 'بنش برس',
      'overhead_press': 'ضغط الأكتاف',
      'barbell_row': 'تجديف بار',
      'skip_setup': 'تخطي الآن',
      'chest_day': 'يوم الصدر',
      'nav_home': 'الرئيسية',
      'nav_quiz': 'الاختبار',
      'nav_progress': 'التقدم',
      'nav_profile': 'حسابي',
      'paused': 'متوقف مؤقتاً',
      'ready_next_session': 'جاهز للجلسة القادمة',
      'last_completed_session': 'آخر جلسة مكتملة',
      'overall_completion': 'إكمال الأسبوع الإجمالي',
    },
    'es': {
      'welcome_user': 'BIENVENIDO/A,\n',
      'sign_in_apple': 'Iniciar sesión con Apple',
      'select_language': 'Seleccionar idioma',
      'success_sub': 'Tu perfil está configurado y tus recomendaciones están listas.',
      'quiz_title': 'ENCUENTRA TU MATCH',
      'quiz_continue': 'CONTINUAR →',
      'quiz_match': 'VER MI MATCH →',
      'quiz_result_label': 'TU MATCH PERFECTO',
      'quiz_result_desc': 'Tu pasión por el rendimiento y el músculo encaja perfectamente con la metodología de {name}.',
      'view_program': 'VER PROGRAMA COMPLETO →',
      'retake_quiz': 'Repetir el Quiz',
      'sessions_completed': 'Sesiones Completadas',
      'training_time': 'Tiempo Total de Entrenamiento',
      'sessions_per_week': 'Sesiones por semana',
      'sessions_goal': 'Últimas 7 semanas · meta: 6/sem',
      'done': 'Hecho',
      'month_streak': 'Racha del Mes',
      'best_streak_ever': 'Mejor racha de la historia',
      'active_program_label': 'PROGRAMA ACTIVO',
      'complete_label': 'completado',
      'week': 'Semana',
      'total_volume': 'Volumen Total Levantado',
      'goal_muscle': 'Ganar Músculo y Fuerza',
      'goal_muscle_sub': 'Hipertrofia, potencia, masa',
      'goal_fat': 'Perder Grasa y Definir',
      'goal_fat_sub': 'Quemar calorías, bajar grasa',
      'goal_endurance': 'Mejorar Resistencia',
      'goal_endurance_sub': 'Cardio, running, larga distancia',
      'goal_performance': 'Rendimiento Atlético',
      'goal_performance_sub': 'Velocidad, agilidad, específico',
      'exp_beg': 'Principiante',
      'exp_beg_sub': 'Menos de 1 año entrenando',
      'exp_int': 'Intermedio',
      'exp_int_sub': '1–3 años de entrenamiento constante',
      'exp_adv': 'Avanzado',
      'exp_adv_sub': '3+ años, atleta serio',
      'time_3': '3 Días a la semana',
      'time_3_sub': 'Sesiones compactas y eficientes',
      'time_5': '4–5 Días a la semana',
      'time_5_sub': 'Entrenamiento dividido equilibrado',
      'time_6': '6 Días a la semana',
      'time_6_sub': 'Modo de compromiso total',
      'personal_info': 'Información Personal',
      'fitness_profile': 'Perfil Fitness',
      'subscription': 'Suscripción',
      'privacy_settings': 'AJUSTES DE PRIVACIDAD',
      'privacy_desc': 'Tu perfil es privado. Solo tú puedes ver tus progresos.',
      'close': 'CERRAR',
      'back': 'Atrás',
      'exercises': 'Ejercicios',
      'style': 'Estilo',
      'intensity': 'Intensidad',
      'training_program': 'Programa de Entrenamiento',
      'focus_areas': 'Zonas de Enfoque',
      'start_this_program': 'EMPEZAR ESTE PROGRAMA',
      'gym_program_builder': 'Constructor de Programas de Gimnasio',
      'end_session': 'FINALIZAR SESIÓN',
      'training': 'ENTRENAMIENTO',
      'exercise': 'Ejercicio',
      'elapsed': 'transcurrido',
      'sets': 'SERIES',
      'reps': 'REPS',
      'rest': 'DESC.',
      'set': 'Serie',
      'prev': 'ANT.',
      'next_exercise': 'SIGUIENTE EJERCICIO',
      'finish_session': 'TERMINAR SESIÓN',
      'session_complete': 'SESIÓN COMPLETADA',
      'session_done_msg': 'Buen trabajo. Descansa, recupérate y vuelve más fuerte.',
      'view_my_progress': 'VER MI PROGRESO',
      'back_to_home': 'Volver al Inicio',
      'bench_press': 'PRESS DE BANCA',
      'overhead_press': 'PRESS MILITAR',
      'barbell_row': 'REMO CON BARRA',
      'skip_setup': 'SALTAR POR AHORA',
      'chest_day': 'DÍA DE PECHO',
      'nav_home': 'Inicio',
      'nav_quiz': 'Quiz',
      'nav_progress': 'Progreso',
      'nav_profile': 'Perfil',
      'paused': 'PAUSADO',
    },
    'hi': {
      'welcome_user': 'स्वागत है,\n',
      'sign_in_apple': 'Apple के साथ साइन इन करें',
      'select_language': 'भाषा चुनें',
      'success_sub': 'आपकी प्रोफाइल सेट हो गई है और आपकी सिफारिशें तैयार हैं।',
      'quiz_title': 'अपना मैच खोजें',
      'quiz_continue': 'जारी रखें →',
      'quiz_match': 'मेरा मैच देखें →',
      'quiz_result_label': 'आपका परफेक्ट मैच',
      'quiz_result_desc': 'प्रदर्शन और मांसपेशियों के लिए आपका जुनून {name} की पद्धति से पूरी तरह मेल खाता है।',
      'view_program': 'पूरा कार्यक्रम देखें →',
      'retake_quiz': 'क्विज़ दोबारा लें',
      'sessions_completed': 'सत्र पूरे हुए',
      'training_time': 'कुल ट्रेनिंग समय',
      'sessions_per_week': 'प्रति सप्ताह सत्र',
      'sessions_goal': 'पिछले 7 सप्ताह · लक्ष्य: 6/सप्ताह',
      'done': 'हो गया',
      'month_streak': 'इस महीने की लकीर',
      'best_streak_ever': 'अब तक की सबसे अच्छी लकीर',
      'active_program_label': 'सक्रिय कार्यक्रम',
      'complete_label': 'पूरा',
      'week': 'सप्ताह',
      'total_volume': 'कुल उठाया गया वजन',
      'goal_muscle': 'मांसपेशियां और ताकत बनाएं',
      'goal_muscle_sub': 'हाइपरट्रॉफी, शक्ति, द्रव्यमान',
      'goal_fat': 'वसा घटाएं और लीन बनें',
      'goal_fat_sub': 'कैलोरी जलाएं, शरीर की चर्बी कम करें',
      'goal_endurance': 'सहनशक्ति और स्टैमिना बनाएं',
      'goal_endurance_sub': 'कार्डियो, दौड़ना, लंबी दूरी',
      'goal_performance': 'एथलेटिक प्रदर्शन',
      'goal_performance_sub': 'गति, चपलता, खेल-विशिष्ट',
      'exp_beg': 'शुरुआती',
      'exp_beg_sub': 'ट्रेनिंग के 1 साल से कम',
      'exp_int': 'मध्यवर्ती',
      'exp_int_sub': '1-3 साल की निरंतर ट्रेनिंग',
      'exp_adv': 'उन्नत',
      'exp_adv_sub': '3+ साल, गंभीर एथलीट',
      'time_3': 'सप्ताह में 3 दिन',
      'time_3_sub': 'कॉम्पैक्ट, कुशल सत्र',
      'time_5': 'सप्ताह में 4-5 दिन',
      'time_5_sub': 'संतुलित स्प्लिट ट्रेनिंग',
      'time_6': 'सप्ताह में 6 दिन',
      'time_6_sub': 'पूर्ण प्रतिबद्धता मोड',
      'personal_info': 'व्यक्तिगत जानकारी',
      'fitness_profile': 'फिटनेस प्रोफाइल',
      'subscription': 'सदस्यता',
      'privacy_settings': 'गोपनीयता सेटिंग्स',
      'privacy_desc': 'आपकी प्रोफाइल वर्तमान में निजी है। केवल आप ही अपनी प्रगति देख सकते हैं।',
      'close': 'बंद करें',
      'back': 'पीछे',
      'exercises': 'व्यायाम',
      'style': 'शैली',
      'intensity': 'तीव्रता',
      'training_program': 'ट्रेनिंग कार्यक्रम',
      'focus_areas': 'फोकस क्षेत्र',
      'start_this_program': 'यह कार्यक्रम शुरू करें',
      'gym_program_builder': 'जिम प्रोग्राम बिल्डर',
      'end_session': 'सत्र समाप्त करें',
      'training': 'ट्रेनिंग',
      'exercise': 'व्यायाम',
      'elapsed': 'बीत गया',
      'sets': 'सेट',
      'reps': 'रेप्स',
      'rest': 'विश्राम',
      'set': 'सेट',
      'prev': 'पिछला',
      'next_exercise': 'अगला व्यायाम',
      'finish_session': 'सत्र पूरा करें',
      'session_complete': 'सत्र पूरा हुआ',
      'session_done_msg': 'अच्छा काम किया। आराम करें और मजबूत होकर वापस आएं।',
      'view_my_progress': 'मेरी प्रगति देखें',
      'back_to_home': 'होम पर वापस',
      'bench_press': 'बेंच प्रेस',
      'overhead_press': 'ओवरहेड प्रेस',
      'barbell_row': 'बारबेल रो',
      'skip_setup': 'अभी छोड़ें',
      'chest_day': 'चेस्ट डे',
      'nav_home': 'होम',
      'nav_quiz': 'क्विज़',
      'nav_progress': 'प्रगति',
      'nav_profile': 'प्रोफ़ाइल',
      'paused': 'रुका हुआ',
    },
    'zh': {
      'welcome_user': '欢迎，\n',
      'sign_in_apple': '使用 Apple 登录',
      'select_language': '选择语言',
      'success_sub': '您的个人资料已设置，个性化建议已就绪。',
      'quiz_title': '寻找您的匹配项',
      'quiz_continue': '继续 →',
      'quiz_match': '查看我的匹配项 →',
      'quiz_result_label': '您的完美匹配',
      'quiz_result_desc': '您对表现和肌肉的追求与 {name} 的方法论完美契合。',
      'view_program': '查看完整计划 →',
      'retake_quiz': '重新测试',
      'sessions_completed': '已完成次数',
      'training_time': '总训练时长',
      'sessions_per_week': '每周训练次数',
      'sessions_goal': '最近 7 周 · 目标：6次/周',
      'done': '已完成',
      'month_streak': '本月连胜',
      'best_streak_ever': '最佳纪录',
      'active_program_label': '当前计划',
      'complete_label': '已完成',
      'week': '周',
      'total_volume': '累计训练容量',
      'goal_muscle': '增加肌肉与力量',
      'goal_muscle_sub': '肌肥大、爆发力、质量',
      'goal_fat': '减脂与塑形',
      'goal_fat_sub': '燃烧热量，降低体脂',
      'goal_endurance': '建立耐力与体力',
      'goal_endurance_sub': '有氧、跑步、长距离',
      'goal_performance': '运动表现',
      'goal_performance_sub': '速度、敏捷、特定运动',
      'exp_beg': '初学者',
      'exp_beg_sub': '训练时间少于 1 年',
      'exp_int': '中级',
      'exp_int_sub': '1-3 年持续训练',
      'exp_adv': '高级',
      'exp_adv_sub': '3 年以上，资深运动员',
      'time_3': '每周 3 天',
      'time_3_sub': '精简高效的训练',
      'time_5': '每周 4-5 天',
      'time_5_sub': '均衡的分化训练',
      'time_6': '每周 6 天',
      'time_6_sub': '全身心投入模式',
      'personal_info': '个人信息',
      'fitness_profile': '运动档案',
      'subscription': '订阅状态',
      'privacy_settings': '隐私设置',
      'privacy_desc': '您的个人资料目前已设为私密。只有您可以看到您的进度。',
      'close': '关闭',
      'back': '返回',
      'exercises': '动作',
      'style': '风格',
      'intensity': '强度',
      'training_program': '训练计划',
      'focus_areas': '重点区域',
      'start_this_program': '开始此计划',
      'gym_program_builder': '健身计划生成器',
      'end_session': '结束训练',
      'training': '训练中',
      'exercise': '动作',
      'elapsed': '已用时间',
      'sets': '组数',
      'reps': '次数',
      'rest': '休息',
      'set': '第',
      'prev': '上一个',
      'next_exercise': '下一个动作',
      'finish_session': '完成训练',
      'session_complete': '训练完成',
      'session_done_msg': '做得好。休息、补能，然后变得更强。',
      'view_my_progress': '查看我的进度',
      'back_to_home': '返回首页',
      'bench_press': '杠铃卧推',
      'overhead_press': '推举',
      'barbell_row': '杠铃划船',
      'skip_setup': '暂时跳过',
      'chest_day': '胸部训练日',
      'nav_home': '首页',
      'nav_quiz': '测试',
      'nav_progress': '进度',
      'nav_profile': '我的',
      'paused': '已暂停',
    },
    'pt': {
      'welcome_user': 'BEM-VINDO,\n',
      'sign_in_apple': 'Entrar com Apple',
      'select_language': 'Selecionar Idioma',
      'success_sub': 'Seu perfil está pronto e suas recomendações personalizadas estão prontas.',
      'quiz_title': 'ENCONTRE SEU PAR',
      'quiz_continue': 'CONTINUAR →',
      'quiz_match': 'VER MEU PAR →',
      'quiz_result_label': 'SEU PAR PERFEITO',
      'quiz_result_desc': 'Seu foco em desempenho e músculo combina perfeitamente com a metodologia de {name}.',
      'view_program': 'VER PROGRAMA COMPLETO →',
      'retake_quiz': 'Refazer o Quiz',
      'sessions_completed': 'Sessões Concluídas',
      'training_time': 'Tempo Total de Treino',
      'sessions_per_week': 'Sessões por semana',
      'sessions_goal': 'Últimas 7 semanas · meta: 6/sem',
      'done': 'Concluído',
      'month_streak': 'Sequência deste Mês',
      'best_streak_ever': 'Melhor sequência de sempre',
      'active_program_label': 'PROGRAMA ATIVO',
      'complete_label': 'concluído',
      'week': 'Semana',
      'total_volume': 'Volume Total Levantado',
      'goal_muscle': 'Ganhar Músculo e Força',
      'goal_muscle_sub': 'Hipertrofia, potência, massa',
      'goal_fat': 'Perder Gordura e Definir',
      'goal_fat_sub': 'Queimar calorias, baixar gordura',
      'goal_endurance': 'Resistência e Stamina',
      'goal_endurance_sub': 'Cardio, corrida, longa distância',
      'goal_performance': 'Desempenho Atlético',
      'goal_performance_sub': 'Velocidade, agilidade, específico',
      'exp_beg': 'Iniciante',
      'exp_beg_sub': 'Menos de 1 ano de treino',
      'exp_int': 'Intermediário',
      'exp_int_sub': '1–3 anos de treino consistente',
      'exp_adv': 'Avançado',
      'exp_adv_sub': '3+ anos, atleta sério',
      'time_3': '3 Dias por semana',
      'time_3_sub': 'Sessões compactas e eficientes',
      'time_5': '4–5 Dias por semana',
      'time_5_sub': 'Treino dividido equilibrado',
      'time_6': '6 Dias por semana',
      'time_6_sub': 'Modo compromisso total',
      'personal_info': 'Informações Pessoais',
      'fitness_profile': 'Perfil Fitness',
      'subscription': 'Assinatura',
      'privacy_settings': 'CONFIGURAÇÕES DE PRIVACIDADE',
      'privacy_desc': 'Seu perfil é privado. Apenas você pode ver seu progresso.',
      'close': 'FECHAR',
      'back': 'Voltar',
      'exercises': 'Exercícios',
      'style': 'Estilo',
      'intensity': 'Intensidade',
      'training_program': 'Programa de Treino',
      'focus_areas': 'Áreas de Foco',
      'start_this_program': 'INICIAR ESTE PROGRAMA',
      'gym_program_builder': 'Construtor de Programa de Academia',
      'end_session': 'ENCERRAR SESSÃO',
      'training': 'TREINO',
      'exercise': 'Exercício',
      'elapsed': 'decorrido',
      'sets': 'SÉRIES',
      'reps': 'REPS',
      'rest': 'REPOUSO',
      'set': 'Série',
      'prev': 'ANT.',
      'next_exercise': 'PRÓXIMO EXERCÍCIO',
      'finish_session': 'CONCLUIR SESSÃO',
      'session_complete': 'SESSÃO CONCLUÍDA',
      'session_done_msg': 'Bom trabalho. Descanse e volte mais forte.',
      'view_my_progress': 'VER MEU PROGRESSO',
      'back_to_home': 'Voltar ao Início',
      'bench_press': 'SUPINO RETO',
      'overhead_press': 'DESENVOLVIMENTO',
      'barbell_row': 'REMADA CURVADA',
      'skip_setup': 'PULAR POR AGORA',
      'chest_day': 'DIA DE PEITO',
      'nav_home': 'Início',
      'nav_quiz': 'Quiz',
      'nav_progress': 'Progresso',
      'nav_profile': 'Perfil',
      'paused': 'PAUSADO',
    },
    'de': {
      'welcome_user': 'WILLKOMMEN,\n',
      'sign_in_apple': 'Mit Apple anmelden',
      'select_language': 'Sprache wählen',
      'success_sub': 'Dein Profil ist bereit und deine Empfehlungen sind fertig.',
      'quiz_title': 'FINDE DEINEN MATCH',
      'quiz_continue': 'WEITER →',
      'quiz_match': 'MEINEN MATCH SEHEN →',
      'quiz_result_label': 'DEIN PERFEKTER MATCH',
      'quiz_result_desc': 'Dein Fokus auf Leistung und Muskeln passt perfekt zur Methodik von {name}.',
      'view_program': 'VOLLSTÄNDIGES PROGRAMM →',
      'retake_quiz': 'Quiz wiederholen',
      'sessions_completed': 'Abgeschlossene Sitzungen',
      'training_time': 'Gesamte Trainingszeit',
      'sessions_per_week': 'Sitzungen pro Woche',
      'sessions_goal': 'Letzte 7 Wochen · Ziel: 6/Woche',
      'done': 'Fertig',
      'month_streak': 'Streak dieses Monats',
      'best_streak_ever': 'Bester Streak jemals',
      'active_program_label': 'AKTIVES PROGRAMM',
      'complete_label': 'abgeschlossen',
      'week': 'Woche',
      'total_volume': 'Gesamtgewicht gehoben',
      'goal_muscle': 'Muskeln & Kraft aufbauen',
      'goal_muscle_sub': 'Hypertrophie, Kraft, Masse',
      'goal_fat': 'Fett verlieren & definieren',
      'goal_fat_sub': 'Kalorien verbrennen, Körperfett senken',
      'goal_endurance': 'Ausdauer & Stamina',
      'goal_endurance_sub': 'Cardio, Laufen, Langstrecke',
      'goal_performance': 'Athletische Leistung',
      'goal_performance_sub': 'Schnelligkeit, Agilität, sportartspezifisch',
      'exp_beg': 'Anfänger',
      'exp_beg_sub': 'Unter 1 Jahr Training',
      'exp_int': 'Fortgeschritten',
      'exp_int_sub': '1–3 Jahre konsistentes Training',
      'exp_adv': 'Profi',
      'exp_adv_sub': '3+ Jahre, ernsthafter Athlet',
      'time_3': '3 Tage pro Woche',
      'time_3_sub': 'Kompakte, effiziente Einheiten',
      'time_5': '4–5 Tage pro Woche',
      'time_5_sub': 'Ausgewogenes Split-Training',
      'time_6': '6 Tage pro Woche',
      'time_6_sub': 'Vollgas-Modus',
      'personal_info': 'Persönliche Infos',
      'fitness_profile': 'Fitness-Profil',
      'subscription': 'Abonnement',
      'privacy_settings': 'DATENSCHUTZ',
      'privacy_desc': 'Dein Profil ist privat. Nur du kannst deinen Fortschritt sehen.',
      'close': 'SCHLIESSEN',
      'back': 'Zurück',
      'exercises': 'Übungen',
      'style': 'Stil',
      'intensity': 'Intensität',
      'training_program': 'Trainingsprogramm',
      'focus_areas': 'Fokusbereiche',
      'start_this_program': 'DIESES PROGRAMM STARTEN',
      'gym_program_builder': 'Gym-Programm-Planer',
      'end_session': 'SITZUNG BEENDEN',
      'training': 'TRAINING',
      'exercise': 'Übung',
      'elapsed': 'vergangen',
      'sets': 'SÄTZE',
      'reps': 'WIDERH.',
      'rest': 'PAUSE',
      'set': 'Satz',
      'prev': 'ZURÜCK',
      'next_exercise': 'NÄCHSTE ÜBUNG',
      'finish_session': 'SITZUNG ABSCHLIESSEN',
      'session_complete': 'SITZUNG ABGESCHLOSSEN',
      'session_done_msg': 'Gute Arbeit. Ruh dich aus und komm stärker zurück.',
      'view_my_progress': 'FORTSCHRITT ANSEHEN',
      'back_to_home': 'Zurück zum Home',
      'bench_press': 'BANKDRÜCKEN',
      'overhead_press': 'SCHULTERDRÜCKEN',
      'barbell_row': 'LANGHANTELRUDERN',
      'skip_setup': 'JETZT ÜBERSPRINGEN',
      'chest_day': 'BRUST-TAG',
      'nav_home': 'Home',
      'nav_quiz': 'Quiz',
      'nav_progress': 'Fortschritt',
      'nav_profile': 'Profil',
      'paused': 'PAUSIERT',
    },
  };

  static String s(BuildContext context, String key) {
    String langCode = Localizations.localeOf(context).languageCode;
    return _localizedValues[langCode]?[key] ?? 
           _localizedValues['en']?[key] ?? 
           '[$key]';
  }
}
