import 'program.dart';
import 'meal.dart';

final List<Program> mockPrograms = [
  Program(
    id: 'arnold',
    type: ProgramType.muscle,
    num: '01 / 06',
    name: 'ARNOLD SCHWARZENEGGER',
    alias: 'The Austrian Oak · Golden Era',
    badge: '⚡ High Volume · Supersets',
    quote: 'Famous for high-volume Agonist/Antagonist supersets — working chest and back together to achieve a massive "pump."',
    setsCount: '5',
    style: 'VOL',
    intensity: 'HIGH',
    tags: ['Chest & Back', 'High Volume', 'Pump Training', 'Compounds'],
    imagePath: 'assets/images/arnold schwarzenegger.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Chest & Back',
        description: 'Primary compound focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Bench Press', detail: '5 sets · 8–12 reps', progress: 0.85),
          WorkoutExercise(name: 'Incline Barbell Press', detail: '5 sets · 8–12 reps', progress: 0.80),
          WorkoutExercise(name: 'Wide-Grip Pull-Ups', detail: '5 sets · to failure', progress: 0.90),
          WorkoutExercise(name: 'Bent-Over Barbell Rows', detail: '5 sets · 8–12 reps', progress: 0.82),
          WorkoutExercise(name: 'Deadlifts', detail: '3 sets · 6–10 reps', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'cbum',
    type: ProgramType.muscle,
    num: '02 / 06',
    name: 'CHRIS BUMSTEAD',
    alias: 'Cbum · Modern Classic Physique',
    badge: '🎯 Controlled Power · Drop Sets',
    quote: 'Uses a mix of heavy compound movements and high-intensity techniques like "drop sets" to maintain his classic silhouette.',
    setsCount: '5',
    style: 'PWR',
    intensity: 'MED',
    tags: ['Classic Lines', 'Drop Sets', 'Mind-Muscle', 'Shoulders'],
    imagePath: 'assets/images/chris bumsted.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Legs & Shoulders',
        description: 'Classic proportions',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Squats', detail: '3 sets · 8–10 reps', progress: 0.88),
          WorkoutExercise(name: 'Leg Press', detail: '3 sets · last set drop', progress: 0.78),
          WorkoutExercise(name: 'Incline DB Press', detail: '3 sets · 8–10 reps', progress: 0.82),
          WorkoutExercise(name: 'Lat Pulldowns', detail: '3 sets · 10–12 reps', progress: 0.74),
          WorkoutExercise(name: 'Lateral Raises', detail: '4 sets · 15 reps', progress: 0.65),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ronaldo',
    type: ProgramType.endurance,
    num: '03 / 06',
    name: 'CRISTIANO RONALDO',
    alias: 'CR7 · Functional Performance',
    badge: '⚽ Speed · Explosive Power',
    quote: 'Focused on explosive speed, lean muscle, and relentless conditioning. The blueprint for elite functional performance.',
    setsCount: '5',
    style: 'FNC',
    intensity: 'MAX',
    tags: ['Functional', 'Explosive', 'Core', 'Endurance'],
    imagePath: 'assets/images/cristiano ronaldo.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Full Body Power',
        description: 'Athletic movement',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Power Cleans', detail: '4 sets · 8 reps', progress: 0.92),
          WorkoutExercise(name: 'Box Jumps', detail: '5 sets · 10 reps', progress: 0.85),
          WorkoutExercise(name: 'Split Squats', detail: '4 sets · 12 reps', progress: 0.78),
          WorkoutExercise(name: 'Plank Holds', detail: '3 sets · 90 sec', progress: 0.88),
          WorkoutExercise(name: 'Spring Sprints', detail: '10 sets · 40m', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ronnie',
    type: ProgramType.muscle,
    num: '04 / 06',
    name: 'RONNIE COLEMAN',
    alias: 'The GOAT · Powerbuilding',
    badge: '🏋️ Extremely Heavy Weight',
    quote: '"Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights." — 8× Mr. Olympia.',
    setsCount: '5',
    style: 'PWB',
    intensity: 'MAX',
    tags: ['Heavy Weight', 'Basic Compounds', 'Max Mass', 'GOAT'],
    imagePath: 'assets/images/ronnie coleman.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Thickess',
        description: 'Pure power',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Deadlifts', detail: '4 sets · 6-12 reps', progress: 1.00),
          WorkoutExercise(name: 'Barbell Squats', detail: '5 sets · 10 reps', progress: 0.96),
          WorkoutExercise(name: 'T-Bar Rows', detail: '4 sets · 10 reps', progress: 0.88),
          WorkoutExercise(name: 'Bench Press', detail: '4 sets · 10 reps', progress: 0.90),
          WorkoutExercise(name: 'Military Press', detail: '4 sets · 10 reps', progress: 0.85),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'phil',
    type: ProgramType.muscle,
    num: '05 / 06',
    name: 'PHIL HEATH',
    alias: 'The Gift · FST-7 Method',
    badge: '🔄 3D Muscle Roundness',
    quote: 'Focused on muscle roundness using FST-7 — 7 sets of an exercise with very short rest periods to maximize fullness.',
    setsCount: '5',
    style: 'FST',
    intensity: 'MED',
    tags: ['FST-7', 'Roundness', '3D Development', 'Detail'],
    imagePath: 'assets/images/phil heath.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Chest & Arms',
        description: 'Detail and fullness',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Incline Flyes', detail: '3 sets · 10 reps', progress: 0.70),
          WorkoutExercise(name: 'Chest Press', detail: '3 sets · 8 reps', progress: 0.78),
          WorkoutExercise(name: 'Lateral Raises', detail: '7 sets · 30s rest', progress: 0.72),
          WorkoutExercise(name: 'Leg Extensions', detail: '7 sets · 12 reps', progress: 0.68),
          WorkoutExercise(name: 'Preacher Curls', detail: '3 sets · 10 reps', progress: 0.65),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'jay',
    type: ProgramType.muscle,
    num: '06 / 06',
    name: 'JAY CUTLER',
    alias: '4× Mr. Olympia · Density',
    badge: '📦 Volume & Consistency',
    quote: 'Known for incredible work capacity — often performing 20+ sets per body part with short rest periods.',
    setsCount: '5',
    style: 'DEN',
    intensity: 'HIGH',
    tags: ['High Volume', 'Consistency', '20+ Sets', 'Short Rest'],
    imagePath: 'assets/images/jay cutler.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Caloric Surp',
        description: 'Density training',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Dumbbell Pullovers', detail: '3 sets · 12 reps', progress: 0.72),
          WorkoutExercise(name: 'Seated Cable Rows', detail: '4 sets · 10 reps', progress: 0.76),
          WorkoutExercise(name: 'Incline BB Press', detail: '4 sets · 10 reps', progress: 0.80),
          WorkoutExercise(name: 'Leg Press', detail: '4 sets · 12 reps', progress: 0.74),
          WorkoutExercise(name: 'Hack Squats', detail: '4 sets · 10 reps', progress: 0.82),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ramon',
    type: ProgramType.muscle,
    num: '07 / 07',
    name: 'RAMON DINO',
    alias: 'The Dino · Classic Pro',
    badge: '🦖 Aesthetic Peak',
    quote: 'Focused on classic proportions with insane muscle density and the most legendary forearms in modern bodybuilding.',
    setsCount: '5',
    style: 'CLS',
    intensity: 'HIGH',
    tags: ['Forearms', 'Back Width', 'Classic Pro', 'Density'],
    imagePath: 'assets/images/ramon dino.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Forearms',
        description: 'Iconic development',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Hammer Curls', detail: '4 sets · 12 reps', progress: 0.88),
          WorkoutExercise(name: 'Lat Pulldowns', detail: '4 sets · 10 reps', progress: 0.82),
          WorkoutExercise(name: 'Reverse Curls', detail: '4 sets · 15 reps', progress: 0.90),
          WorkoutExercise(name: 'Seated Cable Rows', detail: '4 sets · 10 reps', progress: 0.78),
          WorkoutExercise(name: 'Wrist Curls', detail: '4 sets · to failure', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
];

