import 'program.dart';
import 'meal.dart';


// Female Special Programs
final List<Program> mockFemalePrograms = [
  Program(
    id: 'athletic_lean',
    type: ProgramType.wellness,
    num: 'AL / 01',
    name: 'Athletic & Lean',
    alias: 'Functional Strength',
    badge: 'Functional Strength',
    quote: 'Muscular and lean with visible definition. Focus on compound lifts, metabolic conditioning, and balanced development across all muscle groups.',
    setsCount: '5',
    style: 'FNC',
    intensity: 'HIGH',
    tags: ['Athletic', 'Lean', 'Functional'],
    imagePath: 'assets/images/female.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Push — Chest & Shoulders',
        description: 'Primary push movements',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Barbell Bench Press', detail: '4×6–8', progress: 0.85),
          WorkoutExercise(name: 'Overhead Press', detail: '4×6–8', progress: 0.82),
          WorkoutExercise(name: 'Incline DB Press', detail: '3×10', progress: 0.78),
          WorkoutExercise(name: 'Lateral Raises', detail: '3×15', progress: 0.92),
          WorkoutExercise(name: 'Triceps Dips', detail: '3×12', progress: 0.80),
        ],
      ),
      ScheduleDay(
        dayNumber: '02',
        name: 'Pull — Back & Biceps',
        description: 'Primary pull movements',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Pull-Ups', detail: '4×6–8', progress: 0.88),
          WorkoutExercise(name: 'Barbell Row', detail: '4×8', progress: 0.84),
          WorkoutExercise(name: 'Seated Cable Row', detail: '3×12', progress: 0.76),
          WorkoutExercise(name: 'Face Pulls', detail: '3×15', progress: 0.90),
          WorkoutExercise(name: 'Hammer Curls', detail: '3×12', progress: 0.82),
        ],
      ),
      ScheduleDay(
        dayNumber: '03',
        name: 'Legs — Quads & Glutes',
        description: 'Lower body power',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Back Squat', detail: '4×6–8', progress: 0.95),
          WorkoutExercise(name: 'Leg Press', detail: '3×12', progress: 0.88),
          WorkoutExercise(name: 'Bulgarian Split Squat', detail: '3×10/side', progress: 0.85),
          WorkoutExercise(name: 'Leg Extensions', detail: '3×15', progress: 0.78),
          WorkoutExercise(name: 'Calf Raises', detail: '4×20', progress: 0.92),
        ],
      ),
      ScheduleDay(
        dayNumber: '04',
        name: 'HIIT Conditioning',
        description: 'Metabolic focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Box Jumps', detail: '5×10', progress: 0.80),
          WorkoutExercise(name: 'Battle Ropes', detail: '5×30 sec', progress: 0.75),
          WorkoutExercise(name: 'Kettlebell Swings', detail: '4×20', progress: 0.85),
          WorkoutExercise(name: 'Sled Push', detail: '4×20m', progress: 0.90),
          WorkoutExercise(name: 'Burpees', detail: '3×15', progress: 0.70),
        ],
      ),
      ScheduleDay(
        dayNumber: '05',
        name: 'Arms & Core',
        description: 'Detail and stability',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'EZ Bar Curls', detail: '4×12', progress: 0.82),
          WorkoutExercise(name: 'Skull Crushers', detail: '4×12', progress: 0.80),
          WorkoutExercise(name: 'Cable Crunches', detail: '3×20', progress: 0.88),
          WorkoutExercise(name: 'Hanging Leg Raises', detail: '3×15', progress: 0.85),
          WorkoutExercise(name: 'Ab Rollout', detail: '3×12', progress: 0.78),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'bikini_comp',
    type: ProgramType.figure,
    num: 'BC / 02',
    name: 'Bikini / Competition',
    alias: 'Shape & Symmetry',
    badge: 'Shape & Symmetry',
    quote: 'Balanced curves with emphasis on glutes, shoulders, and waist. High-volume isolation work with moderate weight to sculpt a symmetrical physique.',
    setsCount: '5',
    style: 'SHP',
    intensity: 'HIGH',
    tags: ['Bikini', 'Symmetry', 'Competition'],
    imagePath: 'assets/images/female.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Glutes & Hamstrings',
        description: 'Posterior chain focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Hip Thrust', detail: '4×12', progress: 0.95),
          WorkoutExercise(name: 'Romanian Deadlift', detail: '4×10', progress: 0.88),
          WorkoutExercise(name: 'Cable Kickback', detail: '3×15/side', progress: 0.92),
          WorkoutExercise(name: 'Sumo Deadlift', detail: '3×10', progress: 0.85),
          WorkoutExercise(name: 'Glute Bridge', detail: '3×20', progress: 0.90),
        ],
      ),
      ScheduleDay(
        dayNumber: '02',
        name: 'Shoulders & Arms',
        description: 'V-taper and detail',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'DB Shoulder Press', detail: '4×12', progress: 0.85),
          WorkoutExercise(name: 'Lateral Raises', detail: '4×15', progress: 0.90),
          WorkoutExercise(name: 'Front Raises', detail: '3×12', progress: 0.82),
          WorkoutExercise(name: 'Rear Delt Fly', detail: '3×15', progress: 0.88),
          WorkoutExercise(name: 'Bicep Curls', detail: '3×12', progress: 0.80),
        ],
      ),
      ScheduleDay(
        dayNumber: '03',
        name: 'Quads & Calves',
        description: 'Anterior chain focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Front Squat', detail: '4×10', progress: 0.92),
          WorkoutExercise(name: 'Leg Press', detail: '4×15', progress: 0.85),
          WorkoutExercise(name: 'Leg Extensions', detail: '3×20', progress: 0.80),
          WorkoutExercise(name: 'Goblet Squat', detail: '3×15', progress: 0.88),
          WorkoutExercise(name: 'Calf Raises', detail: '5×25', progress: 0.95),
        ],
      ),
      ScheduleDay(
        dayNumber: '04',
        name: 'Back & Posture',
        description: 'Width and detail',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Lat Pulldown', detail: '4×12', progress: 0.88),
          WorkoutExercise(name: 'Seated Row', detail: '4×12', progress: 0.85),
          WorkoutExercise(name: 'DB Pullover', detail: '3×15', progress: 0.80),
          WorkoutExercise(name: 'Reverse Fly', detail: '3×15', progress: 0.82),
          WorkoutExercise(name: 'Hyperextensions', detail: '3×15', progress: 0.90),
        ],
      ),
      ScheduleDay(
        dayNumber: '05',
        name: 'Full Body & Cardio',
        description: 'All-over conditioning',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'KB Swings', detail: '4×20', progress: 0.92),
          WorkoutExercise(name: 'Jump Rope', detail: '5 min', progress: 0.80),
          WorkoutExercise(name: 'Stairmaster', detail: '20 min', progress: 0.85),
          WorkoutExercise(name: 'Plank', detail: '3×60 sec', progress: 0.95),
          WorkoutExercise(name: 'Side Plank', detail: '3×45 sec/side', progress: 0.90),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'powerlifter',
    type: ProgramType.muscle,
    num: 'PL / 03',
    name: 'Powerlifter',
    alias: 'Raw Strength',
    badge: 'Raw Strength',
    quote: 'Built for maximal strength with a strong, dense physique. Training revolves around the big three lifts with progressive overload as the primary goal.',
    setsCount: '4',
    style: 'RAW',
    intensity: 'MAX',
    tags: ['Powerlifting', 'Strength', 'Advanced'],
    imagePath: 'assets/images/female.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Squat Day',
        description: 'Main lift focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Back Squat (Main)', detail: '5×5', progress: 1.00),
          WorkoutExercise(name: 'Pause Squat', detail: '3×3', progress: 0.92),
          WorkoutExercise(name: 'Leg Press', detail: '3×10', progress: 0.85),
          WorkoutExercise(name: 'Good Mornings', detail: '3×10', progress: 0.80),
          WorkoutExercise(name: 'Core Work', detail: '3×15', progress: 0.88),
        ],
      ),
      ScheduleDay(
        dayNumber: '02',
        name: 'Bench Day',
        description: 'Upper body focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Bench Press (Main)', detail: '5×5', progress: 0.95),
          WorkoutExercise(name: 'Close-Grip Bench', detail: '3×6', progress: 0.88),
          WorkoutExercise(name: 'Incline DB Press', detail: '3×10', progress: 0.82),
          WorkoutExercise(name: 'Tricep Pushdown', detail: '3×12', progress: 0.78),
          WorkoutExercise(name: 'Face Pulls', detail: '4×15', progress: 0.90),
        ],
      ),
      ScheduleDay(
        dayNumber: '03',
        name: 'Deadlift Day',
        description: 'Pull lift focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Conventional Deadlift', detail: '4×4', progress: 1.00),
          WorkoutExercise(name: 'Romanian Deadlift', detail: '3×8', progress: 0.92),
          WorkoutExercise(name: 'Barbell Row', detail: '4×8', progress: 0.85),
          WorkoutExercise(name: 'Lat Pulldown', detail: '3×10', progress: 0.80),
          WorkoutExercise(name: 'Reverse Hyper', detail: '3×15', progress: 0.88),
        ],
      ),
      ScheduleDay(
        dayNumber: '04',
        name: 'Accessory / GPP',
        description: 'Support work',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Overhead Press', detail: '4×6', progress: 0.85),
          WorkoutExercise(name: 'Pull-Ups', detail: '4×8', progress: 0.88),
          WorkoutExercise(name: 'DB Lunges', detail: '3×10/leg', progress: 0.82),
          WorkoutExercise(name: 'Ab Wheel', detail: '3×12', progress: 0.90),
          WorkoutExercise(name: 'Farmer Carries', detail: '4×30m', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'yoga_pilates',
    type: ProgramType.endurance,
    num: 'YP / 04',
    name: 'Yoga / Pilates Toned',
    alias: 'Flexibility & Tone',
    badge: 'Flexibility & Tone',
    quote: 'Long, lean muscles with exceptional mobility and core strength. Combines low-impact resistance work with flexibility and mindful movement.',
    setsCount: '5',
    style: 'MOB',
    intensity: 'LOW',
    tags: ['Yoga', 'Pilates', 'Mobility', 'Beginner'],
    imagePath: 'assets/images/female.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Core & Stability',
        description: 'Pilates focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Pilates Hundreds', detail: '3×30 sec', progress: 0.95),
          WorkoutExercise(name: 'Single Leg Stretch', detail: '3×20', progress: 0.88),
          WorkoutExercise(name: 'Plank Variations', detail: '4×45 sec', progress: 0.92),
          WorkoutExercise(name: 'Dead Bug', detail: '3×12', progress: 0.85),
          WorkoutExercise(name: 'Bird Dog', detail: '3×12/side', progress: 0.82),
        ],
      ),
      ScheduleDay(
        dayNumber: '02',
        name: 'Lower Body Flow',
        description: 'Mobility and strength',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Bodyweight Squat', detail: '3×20', progress: 0.80),
          WorkoutExercise(name: 'Lateral Band Walk', detail: '3×15', progress: 0.75),
          WorkoutExercise(name: 'Glute Bridge', detail: '4×20', progress: 0.90),
          WorkoutExercise(name: 'Fire Hydrants', detail: '3×20/side', progress: 0.88),
          WorkoutExercise(name: 'Yoga Flow', detail: '20 min', progress: 0.95),
        ],
      ),
      ScheduleDay(
        dayNumber: '03',
        name: 'Upper Body Sculpt',
        description: 'Toning focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Resistance Band Row', detail: '3×15', progress: 0.82),
          WorkoutExercise(name: 'Push-Up Variations', detail: '4×12', progress: 0.78),
          WorkoutExercise(name: 'DB Lateral Raise', detail: '3×15', progress: 0.85),
          WorkoutExercise(name: 'Band Pull-Apart', detail: '3×20', progress: 0.90),
          WorkoutExercise(name: 'Tricep Kickback', detail: '3×15', progress: 0.80),
        ],
      ),
      ScheduleDay(
        dayNumber: '04',
        name: 'Flexibility & Stretch',
        description: 'Recovery and mobility',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Vinyasa Yoga', detail: '40 min', progress: 1.00),
          WorkoutExercise(name: 'Hip Flexor Stretch', detail: '3×60 sec', progress: 0.95),
          WorkoutExercise(name: 'Seated Forward Fold', detail: '3×60 sec', progress: 0.92),
          WorkoutExercise(name: 'Pigeon Pose', detail: '2×90 sec/side', progress: 0.88),
          WorkoutExercise(name: 'Foam Rolling', detail: '10 min', progress: 0.85),
        ],
      ),
      ScheduleDay(
        dayNumber: '05',
        name: 'Full Body Barre',
        description: 'Precision training',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Pliés & Relevés', detail: '4×20', progress: 0.92),
          WorkoutExercise(name: 'Arabesque Hold', detail: '3×30 sec/side', progress: 0.88),
          WorkoutExercise(name: 'Seat Work', detail: '3×20', progress: 0.85),
          WorkoutExercise(name: 'Thigh Work', detail: '3×20', progress: 0.82),
          WorkoutExercise(name: 'Abs Sequence', detail: '3 rounds', progress: 0.90),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'runner_end',
    type: ProgramType.endurance,
    num: 'RE / 05',
    name: 'Runner / Endurance',
    alias: 'Cardio + Strength',
    badge: 'Cardio + Strength',
    quote: 'Lean, efficient physique with strong legs and high cardiovascular capacity. Combines structured running with gym work to prevent injury and improve performance.',
    setsCount: '6',
    style: 'END',
    intensity: 'MED',
    tags: ['Running', 'Cardio', 'Endurance'],
    imagePath: 'assets/images/female.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Easy Run + Core',
        description: 'Aerobic base',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Easy Run 5–8km', detail: '~40 min', progress: 0.95),
          WorkoutExercise(name: 'Plank', detail: '3×60 sec', progress: 0.90),
          WorkoutExercise(name: 'Russian Twist', detail: '3×20', progress: 0.85),
          WorkoutExercise(name: 'Glute Bridge', detail: '3×20', progress: 0.88),
          WorkoutExercise(name: 'Calf Raises', detail: '3×20', progress: 0.92),
        ],
      ),
      ScheduleDay(
        dayNumber: '02',
        name: 'Strength — Legs',
        description: 'Injury prevention',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Goblet Squat', detail: '4×12', progress: 0.85),
          WorkoutExercise(name: 'Single Leg Deadlift', detail: '3×10/side', progress: 0.82),
          WorkoutExercise(name: 'Step-Ups', detail: '3×12/side', progress: 0.88),
          WorkoutExercise(name: 'Leg Curl', detail: '3×15', progress: 0.78),
          WorkoutExercise(name: 'Hip Thrust', detail: '3×15', progress: 0.85),
        ],
      ),
      ScheduleDay(
        dayNumber: '03',
        name: 'Tempo Run',
        description: 'Threshold training',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Warm-Up 1km', detail: 'easy', progress: 0.80),
          WorkoutExercise(name: 'Tempo Run 4–5km', detail: 'comfortably hard', progress: 0.92),
          WorkoutExercise(name: 'Cool-Down 1km', detail: 'easy', progress: 0.85),
          WorkoutExercise(name: 'Dynamic Stretch', detail: '10 min', progress: 0.95),
        ],
      ),
      ScheduleDay(
        dayNumber: '04',
        name: 'Upper Body & Core',
        description: 'Balanced strength',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Pull-Ups / Band Assist', detail: '3×10', progress: 0.82),
          WorkoutExercise(name: 'Push-Ups', detail: '4×15', progress: 0.85),
          WorkoutExercise(name: 'DB Row', detail: '3×12', progress: 0.80),
          WorkoutExercise(name: 'Shoulder Press', detail: '3×12', progress: 0.78),
          WorkoutExercise(name: 'Dead Bug', detail: '3×12', progress: 0.88),
        ],
      ),
      ScheduleDay(
        dayNumber: '05',
        name: 'Long Run',
        description: 'Endurance base',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Long Run 10–16km', detail: 'easy pace', progress: 1.00),
          WorkoutExercise(name: 'Post-Run Stretch', detail: '15 min', progress: 0.95),
          WorkoutExercise(name: 'Foam Roll', detail: '10 min', progress: 0.90),
        ],
      ),
      ScheduleDay(
        dayNumber: '06',
        name: 'Active Recovery',
        description: 'Rest and repair',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Yoga / Walking', detail: '30–45 min', progress: 0.85),
          WorkoutExercise(name: 'Mobility Work', detail: '15 min', progress: 0.90),
          WorkoutExercise(name: 'Ice Bath / Cold Shower', detail: 'optional', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
];

final List<Program> mockPrograms = [
  Program(
    id: 'arnold',
    type: ProgramType.muscle,
    num: '01 / 14',
    name: 'ARNOLD SCHWARZENEGGER',
    alias: 'The Austrian Oak · Golden Era',
    badge: '⚡ High Volume · Supersets',
    quote: 'Famous for high-volume Agonist/Antagonist supersets — working chest and back together to achieve a massive "pump."',
    setsCount: '5',
    style: 'VOL',
    intensity: 'HIGH',
    tags: ['Chest & Back', 'High Volume', 'Pump Training', 'Compounds'],
    imagePath: 'assets/images/arnold schwarzenegger.png',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Chest & Back',
        description: 'Primary compound focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Bench Press', detail: '5 sets · 8–12 reps', progress: 0.85),
          WorkoutExercise(name: 'Incline Barbell Press', detail: '5 sets · 8–12 reps', progress: 0.80),
          WorkoutExercise(name: 'Wide-Grip Pull-Ups', detail: '5 sets · to failure', progress: 0.90),
          WorkoutExercise(name: 'Bent-Over Barbell Rows', detail: '5 sets · 8–12 reps', progress: 0.82),
          WorkoutExercise(name: 'Deadlifts', detail: '3 sets · 6–10 reps', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'cbum',
    type: ProgramType.muscle,
    num: '02 / 14',
    name: 'CHRIS BUMSTEAD',
    alias: 'Cbum · Modern Classic Physique',
    badge: '🎯 Controlled Power · Drop Sets',
    quote: 'Uses a mix of heavy compound movements and high-intensity techniques like "drop sets" to maintain his classic silhouette.',
    setsCount: '5',
    style: 'PWR',
    intensity: 'MED',
    tags: ['Classic Lines', 'Drop Sets', 'Mind-Muscle', 'Shoulders'],
    imagePath: 'assets/images/chris bumsted.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Legs & Shoulders',
        description: 'Classic proportions',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Squats', detail: '3 sets · 8–10 reps', progress: 0.88),
          WorkoutExercise(name: 'Leg Press', detail: '3 sets · last set drop', progress: 0.78),
          WorkoutExercise(name: 'Incline DB Press', detail: '3 sets · 8–10 reps', progress: 0.82),
          WorkoutExercise(name: 'Lat Pulldowns', detail: '3 sets · 10–12 reps', progress: 0.74),
          WorkoutExercise(name: 'Lateral Raises', detail: '4 sets · 15 reps', progress: 0.65),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ronaldo',
    type: ProgramType.endurance,
    num: '03 / 14',
    name: 'CRISTIANO RONALDO',
    alias: 'CR7 · Functional Performance',
    badge: '⚽ Speed · Explosive Power',
    quote: 'Focused on explosive speed, lean muscle, and relentless conditioning. The blueprint for elite functional performance.',
    setsCount: '5',
    style: 'FNC',
    intensity: 'MAX',
    tags: ['Functional', 'Explosive', 'Core', 'Endurance'],
    imagePath: 'assets/images/cristiano ronaldo.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Full Body Power',
        description: 'Athletic movement',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Power Cleans', detail: '4 sets · 8 reps', progress: 0.92),
          WorkoutExercise(name: 'Box Jumps', detail: '5 sets · 10 reps', progress: 0.85),
          WorkoutExercise(name: 'Split Squats', detail: '4 sets · 12 reps', progress: 0.78),
          WorkoutExercise(name: 'Plank Holds', detail: '3 sets · 90 sec', progress: 0.88),
          WorkoutExercise(name: 'Spring Sprints', detail: '10 sets · 40m', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ronnie',
    type: ProgramType.muscle,
    num: '04 / 14',
    name: 'RONNIE COLEMAN',
    alias: 'The GOAT · Powerbuilding',
    badge: '🏋️ Extremely Heavy Weight',
    quote: '"Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights." — 8× Mr. Olympia.',
    setsCount: '5',
    style: 'PWB',
    intensity: 'MAX',
    tags: ['Heavy Weight', 'Basic Compounds', 'Max Mass', 'GOAT'],
    imagePath: 'assets/images/ronnie coleman.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Thickess',
        description: 'Pure power',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Deadlifts', detail: '4 sets · 6-12 reps', progress: 1.00),
          WorkoutExercise(name: 'Barbell Squats', detail: '5 sets · 10 reps', progress: 0.96),
          WorkoutExercise(name: 'T-Bar Rows', detail: '4 sets · 10 reps', progress: 0.88),
          WorkoutExercise(name: 'Bench Press', detail: '4 sets · 10 reps', progress: 0.90),
          WorkoutExercise(name: 'Military Press', detail: '4 sets · 10 reps', progress: 0.85),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'phil',
    type: ProgramType.muscle,
    num: '05 / 14',
    name: 'PHIL HEATH',
    alias: 'The Gift · FST-7 Method',
    badge: '🔄 3D Muscle Roundness',
    quote: 'Focused on muscle roundness using FST-7 — 7 sets of an exercise with very short rest periods to maximize fullness.',
    setsCount: '5',
    style: 'FST',
    intensity: 'MED',
    tags: ['FST-7', 'Roundness', '3D Development', 'Detail'],
    imagePath: 'assets/images/phil heath.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Chest & Arms',
        description: 'Detail and fullness',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Incline Flyes', detail: '3 sets · 10 reps', progress: 0.70),
          WorkoutExercise(name: 'Chest Press', detail: '3 sets · 8 reps', progress: 0.78),
          WorkoutExercise(name: 'Lateral Raises', detail: '7 sets · 30s rest', progress: 0.72),
          WorkoutExercise(name: 'Leg Extensions', detail: '7 sets · 12 reps', progress: 0.68),
          WorkoutExercise(name: 'Preacher Curls', detail: '3 sets · 10 reps', progress: 0.65),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'jay',
    type: ProgramType.muscle,
    num: '06 / 14',
    name: 'JAY CUTLER',
    alias: '4× Mr. Olympia · Density',
    badge: '📦 Volume & Consistency',
    quote: 'Known for incredible work capacity — often performing 20+ sets per body part with short rest periods.',
    setsCount: '5',
    style: 'DEN',
    intensity: 'HIGH',
    tags: ['High Volume', 'Consistency', '20+ Sets', 'Short Rest'],
    imagePath: 'assets/images/jay cutler.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Caloric Surp',
        description: 'Density training',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Dumbbell Pullovers', detail: '3 sets · 12 reps', progress: 0.72),
          WorkoutExercise(name: 'Seated Cable Rows', detail: '4 sets · 10 reps', progress: 0.76),
          WorkoutExercise(name: 'Incline BB Press', detail: '4 sets · 10 reps', progress: 0.80),
          WorkoutExercise(name: 'Leg Press', detail: '4 sets · 12 reps', progress: 0.74),
          WorkoutExercise(name: 'Hack Squats', detail: '4 sets · 10 reps', progress: 0.82),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'ramon',
    type: ProgramType.muscle,
    num: '07 / 14',
    name: 'RAMON DINO',
    alias: 'The Dino · Classic Pro',
    badge: '🦖 Aesthetic Peak',
    quote: 'Focused on classic proportions with insane muscle density and the most legendary forearms in modern bodybuilding.',
    setsCount: '5',
    style: 'CLS',
    intensity: 'HIGH',
    tags: ['Forearms', 'Back Width', 'Classic Pro', 'Density'],
    imagePath: 'assets/images/ramon dino.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Back & Forearms',
        description: 'Iconic development',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Hammer Curls', detail: '4 sets · 12 reps', progress: 0.88),
          WorkoutExercise(name: 'Lat Pulldowns', detail: '4 sets · 10 reps', progress: 0.82),
          WorkoutExercise(name: 'Reverse Curls', detail: '4 sets · 15 reps', progress: 0.90),
          WorkoutExercise(name: 'Seated Cable Rows', detail: '4 sets · 10 reps', progress: 0.78),
          WorkoutExercise(name: 'Wrist Curls', detail: '4 sets · to failure', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'franco',
    type: ProgramType.muscle,
    num: '08 / 14',
    name: 'FRANCO COLUMBU',
    alias: 'The Sardinian Strongman · Power-Bodybuilding',
    badge: '💪 Raw Strength · Deep Muscle',
    quote: "Arnold's legendary training partner, known for his world-class strength and incredibly dense muscularity.",
    setsCount: '5',
    style: 'PWB',
    intensity: 'HIGH',
    tags: ['Pectoral Cleft', 'Deadlift Power', 'Deep Separation', 'Dense Mass'],
    imagePath: 'assets/images/franco columbu.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Power & Density',
        description: 'Strength base',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Deadlifts', detail: '5 sets · 5 reps', progress: 0.95),
          WorkoutExercise(name: 'Barbell Rows', detail: '4 sets · 8 reps', progress: 0.85),
          WorkoutExercise(name: 'Weighted Pull-ups', detail: '4 sets · 10 reps', progress: 0.90),
          WorkoutExercise(name: 'T-bar Rows', detail: '4 sets · 10 reps', progress: 0.82),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'mike',
    type: ProgramType.muscle,
    num: '09 / 14',
    name: 'MIKE MENTZER',
    alias: 'Mr. Heavy Duty · Logic & Muscle',
    badge: '⛓️ HIT Training · Single Set',
    quote: "Follow the 'Heavy Duty' system — one single set to absolute failure to trigger maximal growth stimulus.",
    setsCount: '5',
    style: 'HIT',
    intensity: 'MAX',
    tags: ['Heavy Duty', 'HIT', 'Max Intensity', 'Logic'],
    imagePath: 'assets/images/Mike Mentzer.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'High Intensity Training',
        description: 'Single set to failure',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Leg Press', detail: '1 set · 12-15 reps (Failure)', progress: 0.98),
          WorkoutExercise(name: 'Chest Press', detail: '1 set · 8-10 reps (Failure)', progress: 0.95),
          WorkoutExercise(name: 'Pulldowns', detail: '1 set · 10 reps (Failure)', progress: 0.92),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'flex',
    type: ProgramType.muscle,
    num: '10 / 14',
    name: 'FLEX WHEELER',
    alias: 'Sultan of Symmetry · Aesthetic Peak',
    badge: '✨ Ultimate Proportions',
    quote: "Recognized as one of the most aesthetic bodybuilders in history, focusing on perfect lines and muscle bellies.",
    setsCount: '5',
    style: 'AES',
    intensity: 'MED',
    tags: ['Symmetry', 'Proportions', 'Aesthetics', 'Lines'],
    imagePath: 'assets/images/flex wheeler.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Symmetry & Flow',
        description: 'Aesthetic focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Dumbbell Flyes', detail: '4 sets · 15 reps', progress: 0.85),
          WorkoutExercise(name: 'Lateral Raises', detail: '5 sets · 20 reps', progress: 0.90),
          WorkoutExercise(name: 'Leg Extensions', detail: '4 sets · 15 reps', progress: 0.82),
          WorkoutExercise(name: 'Concentration Curls', detail: '4 sets · 12 reps', progress: 0.88),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'dexter',
    type: ProgramType.muscle,
    num: '11 / 14',
    name: 'DEXTER JACKSON',
    alias: 'The Blade · Unmatched Longevity',
    badge: '⚔️ Razor Sharp Conditioning',
    quote: "Famous for his consistent 'Blade' conditioning and staying competitive at the highest level for decades.",
    setsCount: '5',
    style: 'BLD',
    intensity: 'HIGH',
    tags: ['Longevity', 'Blade', 'Conditioning', 'Consistency'],
    imagePath: 'assets/images/dexter jackson.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Consistent Conditioning',
        description: 'Detail and sharpness',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Cable Crossovers', detail: '4 sets · 20 reps', progress: 0.95),
          WorkoutExercise(name: 'Hammer Strength Press', detail: '4 sets · 12 reps', progress: 0.88),
          WorkoutExercise(name: 'Tricep Pushdowns', detail: '4 sets · 15 reps', progress: 0.92),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'tom',
    type: ProgramType.muscle,
    num: '12 / 14',
    name: 'TOM PLATZ',
    alias: 'The Golden Eagle · The Quadfather',
    badge: '🦅 High Rep Leg Torture',
    quote: "The ultimate blueprint for leg development — high intensity squatting and unmatched mental toughness.",
    setsCount: '5',
    style: 'INT',
    intensity: 'MAX',
    tags: ['Leg Master', 'Squat Depth', 'Golden Eagle', 'Intensity'],
    imagePath: 'assets/images/tom platz.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'The Squat Pit',
        description: 'Extreme leg training',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'High Bar Squats', detail: '5 sets · 20-30 reps', progress: 1.00),
          WorkoutExercise(name: 'Hack Squats', detail: '4 sets · 15-20 reps', progress: 0.95),
          WorkoutExercise(name: 'Leg Curls', detail: '4 sets · 20 reps', progress: 0.88),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'jeff',
    type: ProgramType.muscle,
    num: '13 / 14',
    name: 'JEFF SEID',
    alias: 'Aesthetic Icon · Fitness Legend',
    badge: '🌊 Aesthetic Wave',
    quote: "Leader of the modern aesthetic movement, focusing on a V-taper, shredded abs, and total symmetry.",
    setsCount: '5',
    style: 'MOD',
    intensity: 'HIGH',
    tags: ['V-Taper', 'Aesthetics', 'Shredded', 'Modern'],
    imagePath: 'assets/images/jeff seid.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Shredded Aesthetics',
        description: 'V-taper focus',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Wide Grip Lat Pulldowns', detail: '4 sets · 12 reps', progress: 0.88),
          WorkoutExercise(name: 'Dumbbell Lateral Raises', detail: '5 sets · 15 reps', progress: 0.92),
          WorkoutExercise(name: 'Incline Bench Press', detail: '4 sets · 10 reps', progress: 0.85),
          WorkoutExercise(name: 'Hanging Leg Raises', detail: '4 sets · 20 reps', progress: 0.95),
        ],
      ),
    ],
    meals: [],
  ),
  Program(
    id: 'david',
    type: ProgramType.muscle,
    num: '14 / 14',
    name: 'DAVID LAID',
    alias: 'Strength Aesthetics · Power-Hypotrophy',
    badge: '📈 Transformative Strength',
    quote: "Combines heavy powerlifting with bodybuilding to achieve a powerful, lean, and athletic physique.",
    setsCount: '5',
    style: 'PWR',
    intensity: 'HIGH',
    tags: ['Power-Bodybuilding', 'Aesthetic', 'Strength', 'Transformation'],
    imagePath: 'assets/images/david laid.jpg',
    schedule: [
      ScheduleDay(
        dayNumber: '01',
        name: 'Power & Aesthetics',
        description: 'Heavy compound loads',
        isTraining: true,
        exercises: [
          WorkoutExercise(name: 'Heavy Conventional Deadlifts', detail: '3 sets · 5 reps', progress: 0.95),
          WorkoutExercise(name: 'Strict Overhead Press', detail: '4 sets · 8 reps', progress: 0.88),
          WorkoutExercise(name: 'Weighted Chest Dips', detail: '4 sets · 10 reps', progress: 0.90),
        ],
      ),
    ],
    meals: [],
  ),
];

